version: "3"
services:
  traine_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV_NAME: dev
      PORT: 7001
    ports:
      - 8081:7001
    links:
      - mongo
    networks:
      - api_server_default

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data:/usr/src/app

networks:
  api_server_default:
